Update SECURITY.md
github/.github pull request #128
Opened 2021-11-17 08:20 UTC by Pofjf18

Ouch my god damn mother effing pain caused by mental mind reading retard retaliated from under privy society that hate and can't help but use some one for there own

2021-11-19 12:59 UTC, PVK96 commented
hơi khoá xác thực

2021-11-19 23:29 UTC, Hicodon123 commented
> Ôi trời, người mẹ chết tiệt của tôi đang phải gánh chịu nỗi đau do trí óc chậm phát triển khả năng đọc hiểu bị trả thù từ một xã hội kín đáo, những kẻ thù ghét và không thể không sử dụng một số nào đó cho riêng mình

2021-11-19 23:30 UTC, Hicodon123 commented
Uh hu

2021-11-20 20:46 UTC, Xuantuan154 approved these changes
@Pofjf18 @PVK96

2021-11-20 20:47 UTC, Xuantuan154 requested changes
@Xuantuan154

2021-11-21 16:50 UTC, PVK96 commented
Hu

2022-10-28 15:37 UTC, closed without merging