Delete SECURITY.md
github/.github pull request #37
Opened 2021-02-26 16:47 UTC by Danvy2709

2021-02-26 18:27 UTC, Danvy2709 commented
2

2021-03-09 20:27 UTC, luismedicina23 approved these changes

2021-03-09 22:12 UTC, luismedicina23 approved these changes
Eu falei foi bem de Vcs 

Falei que era emitente de certificado 

mas que Um bot e 300 pessoas te julgando eh Ridículo e Inválido legalmente no meu país 

But ok

2021-03-09 22:12 UTC, luismedicina23 approved these changes

2021-03-15 19:51 UTC, 0867085052 commented
Hi

2021-04-09 05:34 UTC, tartarza112244 approved these changes

2021-04-27 10:37 UTC, mahiboboo approved these changes

2021-05-02 21:40 UTC, Club-phakmai approved these changes

2021-05-04 20:01 UTC, benkaday3218 approved these changes

2021-05-08 19:54 UTC, champpp96 commented
> Hi



> _No description provided._

2021-06-25 10:18 UTC, goldgoddess21 requested changes
Good

2021-07-28 14:55 UTC, yaddd7 approved these changes

2021-09-14 13:50 UTC, closed without merging

2021-09-14 14:03 UTC, TANATNATH commented
https://github.com/github/.github/pull/69